
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABS AUTHOR BEGIN DOC END ITEM ITEMIZE LB RB SECTION SUBSECTION TEXT TITLEdoc : BEGIN LB DOC RB content END LB DOC RBsectiontext : TEXT\n                    | TEXT BEGIN LB ITEMIZE RB item_list END LB ITEMIZE RB TEXT\n                    | BEGIN LB ITEMIZE RB item_list END LB ITEMIZE RB TEXT\n                    | TEXT BEGIN LB ITEMIZE RB item_list END LB ITEMIZE RBcontent : title abs sections\n                | title author abs sectionstitle : TITLE LB TEXT RBauthor : AUTHOR LB TEXT RBabs : BEGIN LB ABS RB TEXT END LB ABS RBsections : sections section\n                | section\n    section : SECTION LB TEXT RB sectiontext\n                | SUBSECTION LB TEXT RB sectiontext\n                itemize : BEGIN LB ITEMIZE RB item_list END LB ITEMIZE RBitem_list : item_list item\n                 | itemitem : ITEM TEXT'
    
_lr_action_items = {'BEGIN':([0,7,11,31,36,37,38,40,],[2,12,12,-8,-9,42,42,45,]),'$end':([1,32,],[0,-1,]),'LB':([2,8,9,12,13,18,19,42,44,45,59,62,],[3,14,15,21,22,26,27,46,47,48,63,64,]),'DOC':([3,15,],[4,24,]),'RB':([4,23,24,29,30,33,34,49,50,51,65,66,],[5,31,32,35,36,37,38,52,53,54,67,68,]),'TITLE':([5,],[8,]),'END':([6,16,17,25,28,39,40,41,43,55,56,58,60,61,68,69,70,],[9,-6,-12,-11,-7,44,-2,-13,-14,59,-17,62,-16,-18,-5,-4,-3,]),'AUTHOR':([7,31,],[13,-8,]),'SECTION':([10,16,17,20,25,28,40,41,43,53,68,69,70,],[18,18,-12,18,-11,18,-2,-13,-14,-10,-5,-4,-3,]),'SUBSECTION':([10,16,17,20,25,28,40,41,43,53,68,69,70,],[19,19,-12,19,-11,19,-2,-13,-14,-10,-5,-4,-3,]),'TEXT':([14,22,26,27,35,37,38,57,67,68,],[23,30,33,34,39,40,40,61,69,70,]),'ABS':([21,47,],[29,50,]),'ITEMIZE':([46,48,63,64,],[49,51,65,66,]),'ITEM':([52,54,55,56,58,60,61,],[57,57,57,-17,57,-16,-18,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'doc':([0,],[1,]),'content':([5,],[6,]),'title':([5,],[7,]),'abs':([7,11,],[10,20,]),'author':([7,],[11,]),'sections':([10,20,],[16,28,]),'section':([10,16,20,28,],[17,25,17,25,]),'sectiontext':([37,38,],[41,43,]),'item_list':([52,54,],[55,58,]),'item':([52,54,55,58,],[56,56,60,60,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> doc","S'",1,None,None,None),
  ('doc -> BEGIN LB DOC RB content END LB DOC RB','doc',9,'p_doc','LatexParser.py',75),
  ('sectiontext -> TEXT','sectiontext',1,'p_sectiontext','LatexParser.py',82),
  ('sectiontext -> TEXT BEGIN LB ITEMIZE RB item_list END LB ITEMIZE RB TEXT','sectiontext',11,'p_sectiontext','LatexParser.py',83),
  ('sectiontext -> BEGIN LB ITEMIZE RB item_list END LB ITEMIZE RB TEXT','sectiontext',10,'p_sectiontext','LatexParser.py',84),
  ('sectiontext -> TEXT BEGIN LB ITEMIZE RB item_list END LB ITEMIZE RB','sectiontext',10,'p_sectiontext','LatexParser.py',85),
  ('content -> title abs sections','content',3,'p_content','LatexParser.py',96),
  ('content -> title author abs sections','content',4,'p_content','LatexParser.py',97),
  ('title -> TITLE LB TEXT RB','title',4,'p_title','LatexParser.py',124),
  ('author -> AUTHOR LB TEXT RB','author',4,'p_author','LatexParser.py',131),
  ('abs -> BEGIN LB ABS RB TEXT END LB ABS RB','abs',9,'p_abs','LatexParser.py',138),
  ('sections -> sections section','sections',2,'p_sections','LatexParser.py',145),
  ('sections -> section','sections',1,'p_sections','LatexParser.py',146),
  ('section -> SECTION LB TEXT RB sectiontext','section',5,'p_section','LatexParser.py',169),
  ('section -> SUBSECTION LB TEXT RB sectiontext','section',5,'p_section','LatexParser.py',170),
  ('itemize -> BEGIN LB ITEMIZE RB item_list END LB ITEMIZE RB','itemize',9,'p_itemize','LatexParser.py',184),
  ('item_list -> item_list item','item_list',2,'p_item_list','LatexParser.py',191),
  ('item_list -> item','item_list',1,'p_item_list','LatexParser.py',192),
  ('item -> ITEM TEXT','item',2,'p_item','LatexParser.py',201),
]
