
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "DEF IF NUMBER PRINT RETURN VARIABLE WHILEprogram : statementsstatements : statements statement\n                  | statement statement : assignment\n                  | operation\n                  | print\n                  | if\n                  | while\n                  | function\n                  | runfunctionassignment : VARIABLE '=' NUMBERoperation : VARIABLE '=' VARIABLE '+' VARIABLE\n                 | VARIABLE '=' VARIABLE '-' VARIABLEprint : PRINT '(' VARIABLE ')' if : IF '(' condition ')' '{' statements '}' function : DEF VARIABLE '(' VARIABLE ')' '{' statements RETURN VARIABLE '}' runfunction : VARIABLE '(' VARIABLE ')' condition : VARIABLE '>' VARIABLE\n                 | VARIABLE '<' VARIABLEwhile : WHILE '(' condition ')' '{' statements '}' "
    
_lr_action_items = {'RETURN':([4,6,8,9,10,11,14,15,16,29,34,36,44,45,50,51,52,55,],[-5,-7,-3,-6,-9,-4,-10,-8,-2,-11,-14,-17,-13,-12,-20,53,-15,-16,]),'>':([23,],[32,]),')':([24,25,27,30,35,40,41,],[33,34,36,39,43,-19,-18,]),'(':([2,3,12,13,19,],[17,18,20,22,26,]),'+':([28,],[38,]),'=':([12,],[21,]),'-':([28,],[37,]),'NUMBER':([21,],[29,]),'PRINT':([0,1,4,6,8,9,10,11,14,15,16,29,34,36,42,44,45,46,47,48,49,50,51,52,55,],[3,3,-5,-7,-3,-6,-9,-4,-10,-8,-2,-11,-14,-17,3,-13,-12,3,3,3,3,-20,3,-15,-16,]),'WHILE':([0,1,4,6,8,9,10,11,14,15,16,29,34,36,42,44,45,46,47,48,49,50,51,52,55,],[2,2,-5,-7,-3,-6,-9,-4,-10,-8,-2,-11,-14,-17,2,-13,-12,2,2,2,2,-20,2,-15,-16,]),'VARIABLE':([0,1,4,5,6,8,9,10,11,14,15,16,17,18,20,21,22,26,29,31,32,34,36,37,38,42,44,45,46,47,48,49,50,51,52,53,55,],[12,12,-5,19,-7,-3,-6,-9,-4,-10,-8,-2,23,25,27,28,23,35,-11,40,41,-14,-17,44,45,12,-13,-12,12,12,12,12,-20,12,-15,54,-16,]),'{':([33,39,43,],[42,46,48,]),'IF':([0,1,4,6,8,9,10,11,14,15,16,29,34,36,42,44,45,46,47,48,49,50,51,52,55,],[13,13,-5,-7,-3,-6,-9,-4,-10,-8,-2,-11,-14,-17,13,-13,-12,13,13,13,13,-20,13,-15,-16,]),'}':([4,6,8,9,10,11,14,15,16,29,34,36,44,45,47,49,50,52,54,55,],[-5,-7,-3,-6,-9,-4,-10,-8,-2,-11,-14,-17,-13,-12,50,52,-20,-15,55,-16,]),'<':([23,],[31,]),'DEF':([0,1,4,6,8,9,10,11,14,15,16,29,34,36,42,44,45,46,47,48,49,50,51,52,55,],[5,5,-5,-7,-3,-6,-9,-4,-10,-8,-2,-11,-14,-17,5,-13,-12,5,5,5,5,-20,5,-15,-16,]),'$end':([1,4,6,7,8,9,10,11,14,15,16,29,34,36,44,45,50,52,55,],[-1,-5,-7,0,-3,-6,-9,-4,-10,-8,-2,-11,-14,-17,-13,-12,-20,-15,-16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'function':([0,1,42,46,47,48,49,51,],[10,10,10,10,10,10,10,10,]),'statements':([0,42,46,48,],[1,47,49,51,]),'runfunction':([0,1,42,46,47,48,49,51,],[14,14,14,14,14,14,14,14,]),'assignment':([0,1,42,46,47,48,49,51,],[11,11,11,11,11,11,11,11,]),'while':([0,1,42,46,47,48,49,51,],[15,15,15,15,15,15,15,15,]),'program':([0,],[7,]),'statement':([0,1,42,46,47,48,49,51,],[8,16,8,8,16,8,16,16,]),'print':([0,1,42,46,47,48,49,51,],[9,9,9,9,9,9,9,9,]),'operation':([0,1,42,46,47,48,49,51,],[4,4,4,4,4,4,4,4,]),'condition':([17,22,],[24,30,]),'if':([0,1,42,46,47,48,49,51,],[6,6,6,6,6,6,6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements','program',1,'p_program','py_yacc.py',16),
  ('statements -> statements statement','statements',2,'p_statements','py_yacc.py',22),
  ('statements -> statement','statements',1,'p_statements','py_yacc.py',23),
  ('statement -> assignment','statement',1,'p_statement','py_yacc.py',33),
  ('statement -> operation','statement',1,'p_statement','py_yacc.py',34),
  ('statement -> print','statement',1,'p_statement','py_yacc.py',35),
  ('statement -> if','statement',1,'p_statement','py_yacc.py',36),
  ('statement -> while','statement',1,'p_statement','py_yacc.py',37),
  ('statement -> function','statement',1,'p_statement','py_yacc.py',38),
  ('statement -> runfunction','statement',1,'p_statement','py_yacc.py',39),
  ('assignment -> VARIABLE = NUMBER','assignment',3,'p_assignment','py_yacc.py',45),
  ('operation -> VARIABLE = VARIABLE + VARIABLE','operation',5,'p_operation','py_yacc.py',54),
  ('operation -> VARIABLE = VARIABLE - VARIABLE','operation',5,'p_operation','py_yacc.py',55),
  ('print -> PRINT ( VARIABLE )','print',4,'p_print','py_yacc.py',60),
  ('if -> IF ( condition ) { statements }','if',7,'p_if','py_yacc.py',65),
  ('function -> DEF VARIABLE ( VARIABLE ) { statements RETURN VARIABLE }','function',10,'p_function','py_yacc.py',72),
  ('runfunction -> VARIABLE ( VARIABLE )','runfunction',4,'p_runfunction','py_yacc.py',81),
  ('condition -> VARIABLE > VARIABLE','condition',3,'p_condition','py_yacc.py',90),
  ('condition -> VARIABLE < VARIABLE','condition',3,'p_condition','py_yacc.py',91),
  ('while -> WHILE ( condition ) { statements }','while',7,'p_while','py_yacc.py',96),
]
